language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.7-linux64.tar.xz
  - tar xf arduino-1.8.7-linux64.tar.xz
  - sudo mv arduino-1.8.7 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/WEMOS_SHT3x_Arduino_Library
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-library "Adafruit GFX Library"
  - arduino --install-library "Adafruit SSD1306"
  - arduino --install-boards esp8266:esp8266
  - arduino --board esp8266:esp8266:generic:CpuFrequency=80,VTable=flash,FlashFreq=40,FlashMode=qio,FlashSize=512K0,led=2 --save-prefs
  - arduino --get-pref
script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  - arduino --verify $PWD/examples/SHT30_Shield/SHT30_Shield.ino
  # test the main target board, that is Lolin D1 Mini
  - arduino --verify --board esp8266:esp8266:d1_mini:CpuFrequency=80,FlashSize=4M1M $PWD/examples/SHT30_Shield/SHT30_Shield.ino
notifications:
  email:
    on_success: change
    on_failure: change